PORTNAME=		integrity
DISTVERSION=	0.1.0
CATEGORIES=		utils
MASTER_SITES=	https://github.com/greycubesgav/integrity

MAINTAINER=	integrity@greycubes.net
COMMENT=	integrity is a tool for calculating, storing and verifying checksums for files.
WWW=		https://github.com/greycubesgav/integrity

.include <bsd.port.mk>