name: Build MacOS

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
    - run: go version

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: integrity_macos_binaries
        path: bin/integrity*
