name: Integrity Build, Test & Package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: make test

  build:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make build-all

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: integrity_binaries
        path: bin/integrity_*

  package:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies for ruby
      run: |
        apt-get update && apt-get install -y binutils squashfs-tools ruby-full make rpm nodejs

    - name: Install fpm package manager
      run: |
        gem install fpm

    - name: Extract Version
      id: get_version
      run: echo "::set-output name=VERSION::$(make show-version)"

    - name: Build All
      run: make build-all

    - name: Package All
      run: make package-deb-intel

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: integrity_packages  # The name of the artifact
        path: pkgs/*.*  # Path to the built artifact

  package-all:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies for ruby
      run: |
        apt-get update && apt-get install -y binutils squashfs-tools ruby-full make rpm nodejs

    - name: Install fpm package manager
      run: |
        gem install fpm

    - name: Download binaries from buildstep
      uses: actions/download-artifact@v4
      with:
        name: integrity_binaries
        path: bin/

    - name: Package All
      run: make package-all