name: Integrity Build, Test & Package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: make test

  build:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make build-all

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: integrity_binaries
        path: bin/integrity*

  package-intel-deb:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies for ruby
      run: |
        apt-get update && apt-get install -y binutils squashfs-tools ruby-full make rpm nodejs

    - name: Install fpm package manager
      run: |
        gem install fpm

    - name: Extract Version
      id: get_version
      run: echo "{VERSION}={$(make show-version)}" >> $GITHUB_OUTPUT

    - name: Package Linux Debian Intel
      run: make package-deb-intel

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: integrity_debian_intel
        path: pkgs/integrity_*_amd64.deb

  package-intel-slackware:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies for ruby
      run: |
        apt-get update && apt-get install -y binutils squashfs-tools make nodejs

    - name: Package Linux Slackware Intel
      run: make package-slackware-intel

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: integrity_slackware_intel
        path: pkgs/integrity-*.tgz

  package-all:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies for ruby
      run: |
        apt-get update && apt-get install -y binutils squashfs-tools ruby-full make rpm nodejs

    - name: Install fpm package manager
      run: |
        gem install fpm

    - name: Download binaries from buildstep
      uses: actions/download-artifact@v4
      with:
        name: integrity_binaries
        path: bin/

    - name: Display structure of downloaded files
      run: ls -R bin/

    - name: Package All
      run: make package-all

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: integrity_packages
        path: pkgs/*