name: Test, Build & Package

on:
  workflow_dispatch:
  workflow_call:

jobs:

  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
    - run: go version

    - name: Build
      run: make build-all

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: integrity_binaries
        path: bin/integrity*

  package-intel-deb:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
    - run: go version

    - name: Install dependencies for ruby
      run: |
        apt-get update && apt-get install -y binutils squashfs-tools ruby-full make rpm nodejs

    - name: Install fpm package manager
      run: |
        gem install fpm

    - name: Extract Version
      id: get_version
      run: echo "{VERSION}={$(make show-version)}" >> $GITHUB_OUTPUT

    - name: Package Linux Debian Intel
      run: make package-deb-intel

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: integrity_debian_intel
        path: pkgs/integrity_*_amd64.deb

  package-intel-slackware:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
    - run: go version

    - name: Install dependencies for ruby
      run: |
        apt-get update && apt-get install -y binutils squashfs-tools make nodejs

    - name: Package Linux Slackware Intel
      run: make package-slackware-intel

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: integrity_slackware_intel
        path: pkgs/integrity-*.tgz

  package-all:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
    - run: go version

    - name: Install dependencies for ruby
      run: |
        apt-get update && apt-get install -y binutils squashfs-tools ruby-full make rpm nodejs

    - name: Install fpm package manager
      run: |
        gem install fpm

    - name: Download binaries from buildstep
      uses: actions/download-artifact@v4
      with:
        name: integrity_binaries
        path: bin/

    - name: Display structure of downloaded files
      run: ls -R bin/

    - name: Package All
      run: make package-all

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: integrity_packages
        path: pkgs/*