name: Create Release

# Trigger the workflow manually via the GitHub Actions UI
on:

  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:

  package-all:
    uses: ./.github/workflows/package.yml

  create_release:
    needs: package-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Packages from package-all step
      uses: actions/download-artifact@v4
      with:
        name: integrity_packages
        path: pkgs/

    - name: Display structure of downloaded packages
      run: ls -R pkgs/

    - name: Create new release and upload packages
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: pkgs/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        draft: true