name: Test

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: make test